[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[headers]
  for = "/*"
    [headers.values]
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://clinica-psicomotricidade-relacional-api.onrender.com; img-src 'self' data:; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; font-src 'self' data:;"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
